abbrlist = {
  "ain't": "am not",
  "aren't": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "I'm": "I am",
  "Im": "I am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you you will",
  "you'll've": "you you will have",
  "you're": "you are",
  "youre": "you are",
  "you've": "you have",
  "aka": "also known as",
  "afaik": "as far as i know",
  "afk": "away from keyboard",
  "af": "as fuck",
  "asap": "as soon as possible",
  "atk": "at the keyboard",
  "atm": "at the moment",
  "a3": "anytime, anywhere, anyplace",
  "b": "be",
  "bak": "back at keyboard",
  "bbl": "be back later",
  "bbs": "be back soon",
  "bfn": "bye for now",
  "b4n": "bye for now",
  "b4m": "back for more",
  "brb": "be right back",
  "brt": "be right there",
  "btw": "by the way",
  "b4": "before",
  "btc": "bitcoin",
  "cc": "carbon copy",
  "cu": "see you",
  "cul8r": "see you later",
  "cya": "see you",
  "dk": "do not know",
  "diy": "do it yourself",
  "faq": "frequently asked questions",
  "fb": "facebook",
  "fc": "footbal club",
  "fu": "fuck you",
  "fwiw": "for what it's worth",
  "fyi": "for your information",
  "gal": "get a life",
  "gg": "good game",
  "gn": "good night",
  "gmta": "great minds think alike",
  "gr8": "great",
  "g9": "genius",
  "hbd": "happy birthday",
  "hb": "happy birthday",
  "hdy": "how dare you",
  "hdu": "how dare you",
  "hmu": "hit me up",
  "ig": "instagram",
  "ic": "i see",
  "icq": "i seek you",
  "icu": "i see you",
  "ilu": "i love you",
  "imho": "in my honest opinion",
  "imo": "in my opinion",
  "insta": "instagram",
  "iou": "i owe you",
  "iow": "in other words",
  "irl": "in real life",
  "jk": "just kidding",
  "ldr": "long distance relationship",
  "lmao": "laughing my ass of",
  "lil": "little",
  "lol": "laughing out loud",
  "ltns": "long time, no see",
  "ltnc": "long time no see",
  "l8r": "later",
  "luv": "love",
  "lu": "love you",
  "ly": "love you",
  "mte": "my thoughts exactly",
  "m8": "mate",
  "mcd": "mcdonalds",
  "mf": "motherfucker",
  "nrn": "no reply necessary",
  "oic": "oh i see",
  "omg": "oh my god",
  "omfg": "oh my fucking god",
  "org": "organisation",
  "pita": "pain in the ass",
  "pt": "part",
  "pty": "party",
  "prt": "party",
  "prw": "parents are watching",
  "pubg": "player unknowns battleground",
  "qpsa": "que pasa",
  "rofl": "rolling on the floor laughing",
  "roflol": "rolling on the floor laughing out loud",
  "roflmao": "rolling on the floor laughing my ass off",
  "sk8": "skate",
  "s": "yes",
  "asl": "age, sex, location",
  "thx": "thanks",
  "ty": "thank you",
  "thnk": "thank",
  "thnx": "thanks",
  "ttfn": "ta-ta for now",
  "ttyl": "talk to you later",
  "txt": "text",
  "u": "you",
  "u2": "you too",
  "u4e": "yours for ever",
  "wb": "welcome back",
  "wtf": "what the fuck",
  "wtg": "way to go",
  "wuf": "where you from",
  "w8": "wait",
  "y": "why",
  "7k": "sick",
  "pc": "personal computer",
  "@": "at",
  "yolo": "you only live once"
}
